# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02330b19b83a1b7caa9375acdd66761468fd2e1529ad425b4ff41bdab85192e1aeece51f44da7fa105e0439e96136db13aaf36bd85c2ac9294d295d90d4446ef

test:
  secret_key_base: 59e8ba27e3c64deb6c8eacf5715aef5e4bbdc71d0d6fd755d22dbba978b916e7b9af0c124aee760c5fbe50736ba9fa7ff4afd5aef4ad34950c0635933b84e6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
